### ISSUE TITLE
Results wrong when testing at different input resolutions

### ISSUE THREAD

**Issue by ronnie-tian** [cherubicXN/afm_cvpr2019#12]
Hi, I want to test on some other images. When I use the default settings, the result is ok but there are some drifts from the actual edges. I guess it may due to the testing image resolution is too small, so I set the input and output resolutions to 640 and the output is meaningless. Do you have any idea about this? Thank you.

Output using default setting:
![00002 j](https://user-images.githubusercontent.com/12387954/60313434-ad669680-9991-11e9-8807-ad090fd502f5.jpg)

Output with input and output resolutions set to 640:
![00002 j](https://user-images.githubusercontent.com/12387954/60313481-df77f880-9991-11e9-918d-d863047eebee.jpg)

**Comment by cherubicXN** [comment]
Because the training resolution is fixed to 320x320, the test image should also be resized to 320x320. For high resolution images, you should change the resolution of training image and train the network again. I will update the trained models with high resolution training samples recently. You can also do it by yourself.

**Comment by ronnie-tian** [comment]
@cherubicXN Noted, thank you for your reply. I will try to train a model with high resolution.
